import { Component, Input } from '@angular/core';
import { ProductComponent } from '../../shared/components/cards/product/product.component';
import { CommonModule } from '@angular/common';

@Component({
  selector: 'app-products',
  standalone: true,
  templateUrl: './products.component.html',
  styleUrls: ['./products.component.scss'],
  imports: [CommonModule, ProductComponent],
})
export class ProductsComponent {
  products = [
    {
      title: 'Blue Partyhat',
      description: 'Lorem ipsum dolor sit amet consetetur sadpscing elitr.',
      price: '$450.50',
      before: '$522.50',
      logo: 'game_logo.svg',
      image: 'item-1.png',
      in_stock: true,
      on_sale: false,
    },
    {
      title: 'Blue Partyhat',
      description: 'Lorem ipsum dolor sit amet consetetur sadpscing elitr.',
      price: '$450.50',
      before: '$522.50',
      logo: 'game_logo.svg',
      image: 'item-1.png',
      in_stock: false,
      on_sale: true,
    },
    {
      title: 'Blue Partyhat',
      description: 'Lorem ipsum dolor sit amet consetetur sadpscing elitr.',
      price: '$450.50',
      before: '$522.50',
      logo: 'game_logo.svg',
      image: 'item-1.png',
      in_stock: true,
      on_sale: true,
    },
    {
      title: 'Blue Partyhat',
      description: 'Lorem ipsum dolor sit amet consetetur sadpscing elitr.',
      price: '$450.50',
      before: '$522.50',
      logo: 'game_logo.svg',
      image: 'item-2.png',
      in_stock: true,
      on_sale: true,
    },
    {
      title: 'Blue Partyhat',
      description: 'Lorem ipsum dolor sit amet consetetur sadpscing elitr.',
      price: '$450.50',
      before: '$522.50',
      logo: 'game_logo.svg',
      image: 'item-2.png',
      in_stock: true,
      on_sale: true,
    },
    {
      title: 'Blue Partyhat',
      description: 'Lorem ipsum dolor sit amet consetetur sadpscing elitr.',
      price: '$450.50',
      before: '$522.50',
      logo: 'game_logo.svg',
      image: 'item-2.png',
      in_stock: true,
      on_sale: true,
    },
    {
      title: 'Blue Partyhat',
      description: 'Lorem ipsum dolor sit amet consetetur sadpscing elitr.',
      price: '$450.50',
      before: '$522.50',
      logo: 'game_logo.svg',
      image: 'item-3.png',
      in_stock: true,
      on_sale: true,
    },
    {
      title: 'Blue Partyhat',
      description: 'Lorem ipsum dolor sit amet consetetur sadpscing elitr.',
      price: '$450.50',
      before: '$522.50',
      logo: 'game_logo.svg',
      image: 'item-3.png',
      in_stock: true,
      on_sale: true,
    },
    {
      title: 'Blue Partyhat',
      description: 'Lorem ipsum dolor sit amet consetetur sadpscing elitr.',
      price: '$450.50',
      before: '$522.50',
      logo: 'game_logo.svg',
      image: 'item-3.png',
      in_stock: true,
      on_sale: true,
    },
    {
      title: 'Blue Partyhat',
      description: 'Lorem ipsum dolor sit amet consetetur sadpscing elitr.',
      price: '$450.50',
      before: '$522.50',
      logo: 'game_logo.svg',
      image: 'item-4.png',
      in_stock: true,
      on_sale: true,
    },
    {
      title: 'Blue Partyhat',
      description: 'Lorem ipsum dolor sit amet consetetur sadpscing elitr.',
      price: '$450.50',
      before: '$522.50',
      logo: 'game_logo.svg',
      image: 'item-4.png',
      in_stock: true,
      on_sale: true,
    },
    {
      title: 'Blue Partyhat',
      description: 'Lorem ipsum dolor sit amet consetetur sadpscing elitr.',
      price: '$450.50',
      before: '$522.50',
      logo: 'game_logo.svg',
      image: 'item-4.png',
      in_stock: true,
      on_sale: true,
    },
    {
      title: 'Blue Partyhat',
      description: 'Lorem ipsum dolor sit amet consetetur sadpscing elitr.',
      price: '$450.50',
      before: '$522.50',
      logo: 'game_logo.svg',
      image: 'item-5.png',
      in_stock: true,
      on_sale: true,
    },
    {
      title: 'Blue Partyhat',
      description: 'Lorem ipsum dolor sit amet consetetur sadpscing elitr.',
      price: '$450.50',
      before: '$522.50',
      logo: 'game_logo.svg',
      image: 'item-5.png',
      in_stock: true,
      on_sale: true,
    },
    {
      title: 'Blue Partyhat',
      description: 'Lorem ipsum dolor sit amet consetetur sadpscing elitr.',
      price: '$450.50',
      before: '$522.50',
      logo: 'game_logo.svg',
      image: 'item-5.png',
      in_stock: true,
      on_sale: true,
    },
  ];
}
